# Generated by Django 2.2.19 on 2022-09-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20220902_1711"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="URL",
            new_name="slug",
        ),
    ]
