# Generated by Django 2.2.9 on 2022-09-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_auto_20220910_0539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название группы"),
        ),
    ]
