# Generated by Django 2.2.9 on 2022-09-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_auto_20220910_1105"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-pub_date",)},
        ),
    ]
