# Generated by Django 2.2.16 on 2022-12-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_auto_20221219_1827"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузить изображение",
                upload_to="posts/",
                verbose_name="Картинка",
            ),
        ),
    ]
