# Generated by Django 2.2.16 on 2022-12-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20221223_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Подписаться на автора', 'verbose_name_plural': 'Подписки'},
        ),
    ]
