# Generated by Django 2.2.9 on 2022-09-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
